version: "3.8"

services:
  api-gateway:
    image: grrrrr1123/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - eureka-net

  eureka-server:
    image: grrrrr1123/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - eureka-net

  util-service:
    image: grrrrr1123/util-service:latest
    container_name: util-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - eureka-net
networks:
  eureka-net:

