# Stock Service ??
server.port=8081
spring.application.name=stock-service

# Eureka ?? (???: ?? ?? ??)
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=${STOCK_INSTANCE_IP_ADDRESS:localhost}

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# false? ?? ??? ??? ??? ?? ?? ??
eureka.client.enabled=true
# false? ?? ??? apigateway ????  ?? ?? ??
spring.cloud.gateway.discovery.locator.enabled=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# Database ?? (???: ?? ?? ??)
spring.datasource.url=${STOCK_SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/stock_db}
spring.datasource.username=${STOCK_SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=rnskdud1804!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# mybatis
mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# jwt signature
spring.jwt.secret=vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true